#!/usr/bin/env python3
"""
Phase 7C: Generate LaTeX proof scaling summary table from paper-ready CSV.

Real ZK measurements — not cost model.
"""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

from scripts.plot_proof_scaling_figures import (
    PATH_LABELS,
    PATH_ORDER,
    aggregate_by_path_n_sel,
    aggregate_prove_by_path_n_sel,
    load_csv,
)


def build_table_rows(
    gates: dict[str, dict[int, float]],
    prove: dict[str, dict[int, float]],
) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for path in PATH_ORDER:
        g_pts = gates.get(path, {})
        p_pts = prove.get(path, {})
        if not g_pts or not p_pts:
            continue
        n_min = min(g_pts)
        n_max = max(g_pts)
        g_min = g_pts[n_min]
        g_max = g_pts[n_max]
        p_min = p_pts.get(n_min, 0.0)
        p_max = p_pts.get(n_max, 0.0)
        g_ratio = g_max / g_min if g_min > 0 else 0.0
        p_ratio = p_max / p_min if p_min > 0 else 0.0
        rows.append(
            {
                "path": PATH_LABELS[path],
                "gates_min": f"{int(round(g_min)):,}",
                "gates_max": f"{int(round(g_max)):,}",
                "gates_growth": f"{g_ratio:.2f}",
                "prove_min": f"{p_min:.3f}",
                "prove_max": f"{p_max:.3f}",
                "prove_growth": f"{p_ratio:.2f}",
                "n_min": str(n_min),
                "n_max": str(n_max),
            }
        )
    return rows


def render_latex(table_rows: list[dict[str, str]], *, n_sel_range: str) -> str:
    lines = [
        "% Auto-generated by scripts/make_proof_scaling_table.py (Phase 7C)",
        "% Source: auth_zk_paper_ready_summary.csv — median of 3 repeats.",
        f"% N_sel range aggregated across workloads: {n_sel_range}",
        r"\begin{table}[t]",
        r"\centering",
        r"\small",
        r"\caption{Proof cost scaling vs.\ $N_{\mathrm{sel}}$ (synthetic fixed-shape workload).}",
        r"\label{tab:proof-scaling}",
        r"\begin{tabular}{lrrrrrr}",
        r"\toprule",
        "Path & Gates@min & Gates@max & Gate growth & Prove@min (s) & Prove@max (s) & Prove growth \\\\",
        r"\midrule",
    ]
    for r in table_rows:
        lines.append(
            f"{r['path']} & {r['gates_min']} & {r['gates_max']} & {r['gates_growth']} & "
            f"{r['prove_min']} & {r['prove_max']} & {r['prove_growth']} \\\\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}", r"\end{table}", ""])
    return "\n".join(lines)


def make_table(rows: list[dict], output: Path) -> Path:
    if not rows:
        raise ValueError("empty input CSV")

    gates = aggregate_by_path_n_sel(rows)
    prove = aggregate_prove_by_path_n_sel(rows)
    table_rows = build_table_rows(gates, prove)
    if not table_rows:
        raise ValueError("no scaling rows generated")

    n_vals = sorted({int(float(r["N_sel"])) for r in rows})
    n_range = f"{n_vals[0]}--{n_vals[-1]}"
    latex = render_latex(table_rows, n_sel_range=n_range)

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(latex, encoding="utf-8")
    return output


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate RQ6 proof scaling LaTeX table.")
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("artifacts/auth_zk_paper_ready_summary.csv"),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("artifacts/tables/table_proof_scaling_summary.tex"),
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    if not args.input.is_file():
        print(f"error: input not found: {args.input}", file=sys.stderr)
        return 1

    out = make_table(load_csv(args.input), args.output)
    print(f"Wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
