#!/usr/bin/env python3
"""
Phase 7B: Generate LaTeX ACL-class compression table from summary CSV.

Real ZK measurements — not cost model.
"""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

N_ACL_ORDER = (1, 2, 4, 8, 16, 32, 64)


def load_csv(path: Path) -> list[dict]:
    with path.open(newline="") as f:
        return list(csv.DictReader(f))


def _f(row: dict, key: str, default: float = 0.0) -> float:
    raw = row.get(key, "")
    if raw in ("", None):
        return default
    return float(raw)


def filter_workload(
    rows: list[dict],
    *,
    n_probe: int,
    slot_per_list: int,
) -> list[dict]:
    return [
        r
        for r in rows
        if int(float(r["n_probe"])) == n_probe
        and int(float(r["slot_per_list"])) == slot_per_list
        and r["path"] == "auth_acl_class"
    ]


def interpret_sharing(gates_ratio: float) -> str:
    if gates_ratio < 0.95:
        return "strong sharing"
    if gates_ratio <= 1.05:
        return "moderate sharing"
    if gates_ratio <= 1.20:
        return "weak sharing"
    return "degenerate / near object-level"


def build_table_rows(acl_rows: list[dict]) -> list[dict[str, str]]:
    by_n_acl = {int(float(r["N_acl"])): r for r in acl_rows}
    out: list[dict[str, str]] = []
    for n_acl in N_ACL_ORDER:
        if n_acl not in by_n_acl:
            continue
        row = by_n_acl[n_acl]
        gates_r = _f(row, "acl_vs_committed_gates")
        prove_r = _f(row, "acl_vs_committed_prove_time")
        verify = _f(row, "median_verify_time")
        proof_kb = _f(row, "median_proof_size") / 1024.0
        verify_str = f"{verify * 1000:.2f}" if verify < 0.01 else f"{verify:.3f}"
        out.append(
            {
                "n_acl": str(n_acl),
                "gates_ratio": f"{gates_r:.2f}",
                "prove_ratio": f"{prove_r:.2f}",
                "verify": verify_str,
                "proof_kb": f"{proof_kb:.1f}",
                "interpretation": interpret_sharing(gates_r),
            }
        )
    return out


def render_latex(table_rows: list[dict[str, str]], *, n_sel: int, n_repeats: int) -> str:
    verify_unit = "ms" if table_rows and float(table_rows[0]["verify"]) < 10 else "s"
    lines = [
        "% Auto-generated by scripts/make_acl_class_table.py (Phase 7B)",
        "% Source: auth_zk_acl_class_summary_repeat3.csv — median of repeats.",
        f"% Workload: N_sel={n_sel}, n_repeats={n_repeats}",
        r"\begin{table}[t]",
        r"\centering",
        r"\small",
        r"\caption{ACL-class compression vs.\ object-level committed auth (gates ratio; committed = 1.0).}",
        r"\label{tab:acl-class}",
        r"\begin{tabular}{rrrrrl}",
        r"\toprule",
        f"$N_{{\\mathrm{{acl}}}}$ & Gates ratio & Prove ratio & Verify ({verify_unit}) & Size (KB) & Interpretation \\\\",
        r"\midrule",
    ]
    for r in table_rows:
        lines.append(
            f"{r['n_acl']} & {r['gates_ratio']} & {r['prove_ratio']} & "
            f"{r['verify']} & {r['proof_kb']} & {r['interpretation']} \\\\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}", r"\end{table}", ""])
    return "\n".join(lines)


def make_table(
    summary_rows: list[dict],
    output: Path,
    *,
    n_probe: int = 4,
    slot_per_list: int = 64,
) -> Path:
    acl_rows = filter_workload(summary_rows, n_probe=n_probe, slot_per_list=slot_per_list)
    if not acl_rows:
        raise ValueError("no auth_acl_class rows for selected workload")

    table_rows = build_table_rows(acl_rows)
    n_sel = int(float(acl_rows[0]["N_sel"]))
    n_repeats = int(float(acl_rows[0]["n_repeats"]))
    latex = render_latex(table_rows, n_sel=n_sel, n_repeats=n_repeats)

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(latex, encoding="utf-8")
    return output


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate RQ3 ACL-class LaTeX table.")
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("artifacts/auth_zk_acl_class_summary_repeat3.csv"),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("artifacts/tables/table_acl_class_summary.tex"),
    )
    parser.add_argument("--n-probe", type=int, default=4)
    parser.add_argument("--slot-per-list", type=int, default=64)
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    if not args.input.is_file():
        print(f"error: input not found: {args.input}", file=sys.stderr)
        return 1

    out = make_table(
        load_csv(args.input),
        args.output,
        n_probe=args.n_probe,
        slot_per_list=args.slot_per_list,
    )
    print(f"Wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
