#!/usr/bin/env python3
"""
Phase 7A: Generate LaTeX proof overhead table from paper-ready summary CSV.

Real ZK measurements — not cost model. Does not re-run proofs.
"""

from __future__ import annotations

import argparse
import csv
import statistics
import sys
from pathlib import Path

from scripts.plot_proof_overhead_figures import (
    PATH_ORDER,
    PATH_SHORT_LABELS,
    filter_workload,
    ordered_paths,
    pick_representative_workload,
    rows_by_path,
)

PAPER_PATH_LABELS = {
    "baseline": "Content-only",
    "auth_all_visible": "Auth-mask",
    "auth_policy": "Policy",
    "auth_committed": "Committed-auth",
    "auth_slot_aligned": "Slot-aligned",
    "auth_acl_class": "ACL-class",
}


def load_csv(path: Path) -> list[dict]:
    with path.open(newline="") as f:
        return list(csv.DictReader(f))


def _metric(row: dict, *keys: str) -> float:
    for key in keys:
        if key in row and row[key] not in ("", None):
            return float(row[key])
    return 0.0


def median_memory_by_path(
    metrics_rows: list[dict],
    *,
    n_probe: int,
    slot_per_list: int,
) -> dict[str, float]:
    grouped: dict[str, list[float]] = {}
    for row in metrics_rows:
        if int(float(row["n_probe"])) != n_probe:
            continue
        if int(float(row["slot_per_list"])) != slot_per_list:
            continue
        path = row["path"]
        grouped.setdefault(path, []).append(_metric(row, "memory"))
    return {p: float(statistics.median(vals)) for p, vals in grouped.items() if vals}


def format_verify_time(seconds: float) -> str:
    if seconds < 0.01:
        return f"{seconds * 1000:.2f}"
    return f"{seconds:.3f}"


def verify_time_unit(seconds: float) -> str:
    return "ms" if seconds < 0.01 else "s"


def format_proof_size_kb(size_bytes: float) -> str:
    return f"{size_bytes / 1024.0:.1f}"


def format_memory_mb(mem_bytes: float) -> str:
    if mem_bytes <= 0:
        return "---"
    return f"{mem_bytes / (1024.0 * 1024.0):.1f}"


def build_table_rows(
    by_path: dict[str, dict],
    paths: list[str],
    memory_by_path: dict[str, float],
) -> list[dict[str, str]]:
    baseline = by_path["baseline"]
    b_gates = _metric(baseline, "median_gates", "gates")
    b_prove = _metric(baseline, "median_prove_time", "prove_time")
    b_verify = _metric(baseline, "median_verify_time", "verify_time")
    use_ms = b_verify < 0.01

    out: list[dict[str, str]] = []
    for path in paths:
        row = by_path[path]
        gates = _metric(row, "median_gates", "gates")
        prove = _metric(row, "median_prove_time", "prove_time")
        verify = _metric(row, "median_verify_time", "verify_time")
        proof_size = _metric(row, "median_proof_size", "proof_size")
        mem = memory_by_path.get(path, 0.0)

        gates_oh = gates / b_gates if b_gates > 0 else 0.0
        prove_oh = prove / b_prove if b_prove > 0 else 0.0

        if use_ms:
            verify_str = f"{verify * 1000:.2f}"
        else:
            verify_str = f"{verify:.3f}"

        out.append(
            {
                "path": PAPER_PATH_LABELS.get(path, path),
                "gates": f"{gates:.0f}",
                "prove_s": f"{prove:.3f}",
                "verify": verify_str,
                "verify_unit": "ms" if use_ms else "s",
                "proof_kb": format_proof_size_kb(proof_size),
                "memory_mb": format_memory_mb(mem),
                "gates_oh": f"{gates_oh:.2f}",
                "prove_oh": f"{prove_oh:.2f}",
            }
        )
    return out


def render_latex(
    table_rows: list[dict[str, str]],
    *,
    n_probe: int,
    slot_per_list: int,
    n_sel: int,
    verify_unit: str,
    has_memory: bool,
) -> str:
    verify_header = f"Verify ({verify_unit})"
    mem_col = " & Memory (MB)" if has_memory else ""
    mem_fmt = " & {memory_mb}" if has_memory else ""

    lines = [
        "% Auto-generated by scripts/make_proof_overhead_table.py (Phase 7A)",
        "% Source: artifacts/auth_zk_paper_ready_summary.csv — existing ZK bench, not re-run.",
        "% Content-only = V3DB-shaped baseline; AuthView paths are additive extensions.",
        f"% Workload: n_probe={n_probe}, slot_per_list={slot_per_list}, N_sel={n_sel}",
        r"\begin{table}[t]",
        r"\centering",
        r"\small",
        r"\caption{Proof overhead vs.\ content-only baseline (median of 3 repeats, synthetic fixed-shape workload).}",
        r"\label{tab:proof-overhead}",
        r"\begin{tabular}{lrrrrrr}",
        r"\toprule",
        f"Path & Gates & Prove (s) & {verify_header} & Size (KB){mem_col} & Gates OH & Prove OH \\\\",
        r"\midrule",
    ]

    for r in table_rows:
        mem_part = mem_fmt.format(memory_mb=r["memory_mb"]) if has_memory else ""
        lines.append(
            f"{r['path']} & {r['gates']} & {r['prove_s']} & {r['verify']} & "
            f"{r['proof_kb']}{mem_part} & {r['gates_oh']} & {r['prove_oh']} \\\\"
        )

    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}",
            r"\end{table}",
            "",
        ]
    )
    return "\n".join(lines)


def make_table(
    summary_rows: list[dict],
    output: Path,
    *,
    n_probe: int | None,
    slot_per_list: int | None,
    metrics_path: Path | None,
) -> Path:
    if not summary_rows:
        raise ValueError("empty summary CSV")

    if n_probe is None and slot_per_list is None:
        n_probe, slot_per_list, _ = pick_representative_workload(summary_rows)

    workload = filter_workload(
        summary_rows, n_probe=n_probe, slot_per_list=slot_per_list, n_sel=None
    )
    if not workload:
        raise ValueError("no rows match workload filter")

    by_path = rows_by_path(workload)
    if "baseline" not in by_path:
        raise ValueError("baseline path missing")

    paths = ordered_paths(by_path)
    n_sel = int(float(workload[0]["N_sel"]))

    memory_by_path: dict[str, float] = {}
    if metrics_path and metrics_path.is_file():
        memory_by_path = median_memory_by_path(
            load_csv(metrics_path),
            n_probe=n_probe,
            slot_per_list=slot_per_list,
        )

    table_rows = build_table_rows(by_path, paths, memory_by_path)
    verify_unit = table_rows[0]["verify_unit"] if table_rows else "ms"
    has_memory = any(v > 0 for v in memory_by_path.values())

    latex = render_latex(
        table_rows,
        n_probe=n_probe,
        slot_per_list=slot_per_list,
        n_sel=n_sel,
        verify_unit=verify_unit,
        has_memory=has_memory,
    )

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(latex, encoding="utf-8")
    return output


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate RQ2 proof overhead LaTeX table.")
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("artifacts/auth_zk_paper_ready_summary.csv"),
    )
    parser.add_argument(
        "--metrics",
        type=Path,
        default=Path("artifacts/auth_zk_paper_ready_metrics.csv"),
        help="Optional raw metrics for median memory column.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("artifacts/tables/table_proof_overhead.tex"),
    )
    parser.add_argument("--n-probe", type=int, default=None)
    parser.add_argument("--slot-per-list", type=int, default=None)
    parser.add_argument("--no-metrics", action="store_true")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    if not args.input.is_file():
        print(f"error: input not found: {args.input}", file=sys.stderr)
        return 1

    metrics = None if args.no_metrics else args.metrics
    out = make_table(
        load_csv(args.input),
        args.output,
        n_probe=args.n_probe,
        slot_per_list=args.slot_per_list,
        metrics_path=metrics,
    )
    print(f"Wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
