#!/usr/bin/env python3
"""
Phase 8C: LaTeX table for public utility baseline summary CSV.
"""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path


def load_csv(path: Path) -> list[dict]:
    with path.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def _f(row: dict, key: str, default: float = 0.0) -> float:
    raw = row.get(key, "")
    if raw in ("", None):
        return default
    return float(raw)


def _fmt_recall(v: float) -> str:
    return f"{v:.3f}"


def _fmt_time(v: float) -> str:
    if v <= 0:
        return "---"
    if v < 10:
        return f"{v:.2f}"
    return f"{v:.1f}"


def _fmt_qps(row: dict) -> str:
    qps = row.get("qps", "")
    if qps in ("", None):
        qt = _f(row, "query_time_s")
        nq = _f(row, "num_queries")
        if qt > 0 and nq > 0:
            return f"{nq / qt:.1f}"
        return "---"
    return f"{float(qps):.1f}"


def render_table(rows: list[dict]) -> str:
    rows = [r for r in rows if r.get("scheme", "standard") == "standard"]
    order = [
        ("sift1m", "high-acc"),
        ("sift1m", "zk-opt"),
        ("gist1m", "high-acc"),
        ("gist1m", "zk-opt"),
    ]
    by_key = {(r["dataset"], r["config"]): r for r in rows}

    lines = [
        "% Auto-generated by scripts/make_public_utility_table.py (Phase 8C)",
        "\\begin{table}[t]",
        "\\centering",
        "\\small",
        "\\begin{tabular}{llrrrrrrr}",
        "\\toprule",
        "Dataset & Config & $n_{list}$ & $n_{probe}$ & $B_c$ "
        "& R@1 & R@10 & R@100 & QPS \\\\",
        "\\midrule",
    ]

    for key in order:
        row = by_key.get(key)
        if row is None:
            continue
        ds = "SIFT1M" if row["dataset"] == "sift1m" else "GIST1M"
        cfg = row["config"].replace("-", "\\mbox{-}")
        lines.append(
            f"{ds} & {cfg} & {int(float(row['n_list']))} & {int(float(row['n_probe']))} "
            f"& {int(float(row['cluster_bound']))} "
            f"& {_fmt_recall(_f(row, 'recall_at_1'))} "
            f"& {_fmt_recall(_f(row, 'recall_at_10'))} "
            f"& {_fmt_recall(_f(row, 'recall_at_100'))} "
            f"& {_fmt_qps(row)} \\\\"
        )

    lines.extend(["\\bottomrule", "\\end{tabular}", "\\caption{Public IVF-PQ utility baseline (standard path, full SIFT1M/GIST1M).}", "\\label{tab:public-utility}", "\\end{table}", ""])
    return "\n".join(lines)


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate public utility LaTeX table.")
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("artifacts/public_utility/sift_gist_utility_summary.csv"),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("artifacts/tables/table_public_utility_summary.tex"),
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    root = Path(__file__).resolve().parents[1]
    input_path = args.input if args.input.is_absolute() else root / args.input
    output_path = args.output if args.output.is_absolute() else root / args.output
    output_path.parent.mkdir(parents=True, exist_ok=True)
    tex = render_table(load_csv(input_path))
    output_path.write_text(tex, encoding="utf-8")
    print(f"Wrote {output_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
