#!/usr/bin/env python3
"""Phase 9B: LaTeX table for full authorized-reference calibration."""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

CONFIG_ORDER = [
    ("sift1m", "high-acc"),
    ("sift1m", "zk-opt"),
    ("gist1m", "high-acc"),
    ("gist1m", "zk-opt"),
]
POLICY_ORDER = ("uniform_random", "clustered_acl", "skewed_acl")
SELECTIVITIES = (0.1, 0.25, 0.5, 0.75)
K = 10


def load_csv(path: Path) -> list[dict]:
    with path.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def _f(row: dict, key: str, default: float = 0.0) -> float:
    raw = row.get(key, "")
    if raw in ("", None):
        return default
    return float(raw)


def _fmt(v: float) -> str:
    return f"{v:.3f}"


def render_table(rows: list[dict]) -> str:
    rows_k = [r for r in rows if int(float(r.get("k", 0))) == K]
    by_key = {
        (r["dataset"], r["config"], r["policy_mode"], round(_f(r, "selectivity"), 4)): r
        for r in rows_k
    }
    lines = [
        "% Auto-generated by scripts/make_authorized_calibration_table.py (Phase 9B)",
        "% reference_scope=full_base_calibration",
        "\\begin{table}[t]",
        "\\centering",
        "\\small",
        "\\begin{tabular}{lllrrrrr}",
        "\\toprule",
        "Dataset & Config & Policy & Sel. "
        "& Post & Cand. & Full & $\\Delta$(cand$-$full) \\\\",
        "\\midrule",
    ]
    for dataset, config in CONFIG_ORDER:
        ds = "SIFT1M" if dataset == "sift1m" else "GIST1M"
        cfg = config.replace("-", "\\mbox{-}")
        for policy in POLICY_ORDER:
            pl = policy.replace("_", "\\_")
            for sel in SELECTIVITIES:
                row = by_key.get((dataset, config, policy, sel))
                if row is None:
                    continue
                lines.append(
                    f"{ds} & {cfg} & {pl} & {sel:.2f} "
                    f"& {_fmt(_f(row, 'post_filter_recall'))} "
                    f"& {_fmt(_f(row, 'candidate_reference_recall'))} "
                    f"& {_fmt(_f(row, 'full_authorized_recall'))} "
                    f"& {_fmt(_f(row, 'candidate_full_recall_gap'))} \\\\"
                )
        lines.append("\\midrule")
    if lines[-1] == "\\midrule":
        lines.pop()
    lines.extend(
        [
            "\\bottomrule",
            "\\end{tabular}",
            "\\caption{Full-base authorized reference calibration (R@10; candidate vs full gap).}",
            "\\label{tab:auth-calibration}",
            "\\end{table}",
        ]
    )
    return "\n".join(lines) + "\n"


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Make auth calibration LaTeX table.")
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("artifacts/auth_calibration/full_authorized_reference_summary.csv"),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("artifacts/tables/table_authorized_reference_calibration.tex"),
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    root = Path(__file__).resolve().parents[1]
    input_path = args.input if args.input.is_absolute() else root / args.input
    output_path = args.output if args.output.is_absolute() else root / args.output
    rows = load_csv(input_path)
    if not rows:
        raise SystemExit(f"no rows in {input_path}")
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_table(rows), encoding="utf-8")
    print(f"Wrote {output_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
